### ISSUE TITLE
Samsung Galaxy Book Go (Snapdragon 7c gen 2)

### ISSUE THREAD

**Issue by ghost** [WOA-Project/Qualcomm-Reference-Drivers#2]
Hello. Are there Samsung Galaxy Book Go (Snapdragon 7c gen 2) of the drivers? They don't work on that.

**Comment by gus33000** [comment]
Hi, this repository is meant to hold drivers for Qualcomm reference devices, with the exception of Microsoft ones added as well. It is not the goal of this repository to hold oem device drivers like for your Samsung device. You may want to contact your original equipment manufacturer to get a copy of their drivers. We will not provide them in this repository nor can we get them for you actually.

Hope you understand,
-gus
