### ISSUE TITLE
Questions about driver fetching

### ISSUE THREAD

**Issue by AceDroidX** [WOA-Project/Qualcomm-Reference-Drivers#3]
How are the drivers for the project fetched?
Are they packaged from the DriverStore of the actual machine or are they obtained from the Windows Update API?

I have a Huawei Matebook E Go using 8cx gen 3 but the OEM rarely updates the drivers, most of them are stuck at 2022/10.
However, I've found that most of the 8280_QRD drivers are compatible with this device, and the device has become much more stable after updating with these drivers.
It would be helpful to know how to get the drivers.

**Comment by gus33000** [comment]
Hi! Sorry for the late reply. They indeed are from Windows Update with specific parameters for enrolling into a specific driver flight qualcomm uses for their devices. It's a bit late for me to detail this so I will do later than now sorry. Just wanted to reply to not miss this issue again ^^

**Comment by gus33000** [comment]
Hi, you can find a code sample here for doing so on your own if you want: https://github.com/gus33000/UUPMediaCreator/tree/temp/driverfetch

**Comment by AceDroidX** [comment]
Thanks!
