### ISSUE TITLE
How to install the drivers?

### ISSUE THREAD

**Issue by schranzonator** [WOA-Project/Qualcomm-Reference-Drivers#4]
Hi, for sure a silly question ^^ but how to install the drivers? Just executing the .cab files? I mainly work with linux so i have no experience with windows drivers. My device (Miix 630) wont install these drivers over windows update automatically cause the device has no UUID in the BIOS, i think the mainboard was switched some time ago. Thanks in advance.

**Comment by woachk** [comment]
Extract the .cab then right click -> Install on the .inf

**Comment by schranzonator** [comment]
Allright i installed all 86 drivers, the newest version, but audio and stylus are not working. Is there anything else to consider? In device manager it says Firmware-Update-Ressource is wrong version (v1.0.1075.2508).

**Comment by gus33000** [comment]
I'm not sure we can help you here, sounds like the id wouldn't be shown and you would be on a different firmware that wouldn't be updatable to the capsule we collect. We only collect drivers from WU, maybe you could ask for support from the oem directly? Not sure what could be done :/
